SCHEMA_VERSION="0.6.7.4"
CHANNELS={"mela99.com":["bg","en","ru"],"m99.eu":["bg","en","ru"],"rabotni-drehi.com":["bg","en","ru"],"medicinski-drehi.com":["bg","en","ru"],"laviro.ro":["ro","en"],"alviro.ro":["ro","en"]}
FACTS={"brand":"Cherokee","collection":"WW Revolution","style":"WW601","supplier_alias":"WWE601","manufacturer_item":"CK-WW601--","colour":"Navy","material":"78% polyester, 20% rayon, 2% spandex","fit":"Missy relaxed fit","center_back_length_inches":26,"neckline":"Curved V-neckline","sleeves":"Short sleeves","pockets":"2 front patch pockets with instrument loops","mesh_side_panels":True,"shirttail_hem":True,"fabric":"Silky stretch twill fabric","supplier_visible_sizes":["2XS","XS","S","M","L","XL","2XL"]}
def document(lang):
 data={
 "bg":["Дамска медицинска туника Cherokee WW Revolution WW601 Navy","Cherokee WW601 Navy дамска медицинска туника | M99","Дамска медицинска туника Cherokee WW601 Navy с еластична материя, V-образно деколте, два предни джоба и мрежести странични панели.",["Дизайн и кройка","Материя и комфорт","Джобове и функционалност","Технически характеристики","Размери","Често задавани въпроси"]],
 "en":["Cherokee WW Revolution WW601 Navy Women's Scrub Top","Cherokee WW601 Navy Women's Scrub Top | M99","Cherokee WW601 Navy women's scrub top with stretch fabric, curved V-neck, two front patch pockets and mesh side panels.",["Design and fit","Fabric and comfort","Pockets and functionality","Technical specifications","Sizes","Frequently asked questions"]],
 "ru":["Женская медицинская туника Cherokee WW Revolution WW601 Navy","Cherokee WW601 Navy женская медицинская туника | M99","Женская медицинская туника Cherokee WW601 Navy: эластичная ткань, V-образный вырез, два передних кармана и сетчатые боковые панели.",["Дизайн и посадка","Материал и комфорт","Карманы и функциональность","Технические характеристики","Размеры","Часто задаваемые вопросы"]],
 "ro":["Bluză medicală damă Cherokee WW Revolution WW601 Navy","Cherokee WW601 Navy bluză medicală damă | M99","Bluză medicală damă Cherokee WW601 Navy cu material elastic, decolteu în V, două buzunare frontale și panouri laterale din plasă.",["Design și croială","Material și confort","Buzunare și funcționalitate","Specificații tehnice","Mărimi","Întrebări frecvente"]]}
 n,t,m,h=data[lang]
 return {"name":n,"h1":n,"meta_title":t,"meta_description":m,"h2":h,"faq_count":6,"facts_used":["material","fit","center_back_length_inches","neckline","sleeves","pockets","mesh_side_panels","shirttail_hem","fabric"],"supplier_market_enrichment":["supplier_alias","supplier_visible_sizes"],"supplier_text_copied_verbatim":False}
def build_preview():
 return {"schema_version":SCHEMA_VERSION,"mode":"FULL_MULTILINGUAL_CANONICAL_CONTENT_PREVIEW","write_allowed":False,"identity":{"brand":"Cherokee","collection":"WW Revolution","style":"WW601","supplier_alias":"WWE601","manufacturer_item":"CK-WW601--","colour":"Navy"},"facts":FACTS,"provenance":{"technical_facts":"manufacturer","supplier_alias_and_visible_sizes":"exact Stenso product","price":"NOT SELECTED","stock":"NOT CLAIMED"},"channel_language_policy":CHANNELS,"documents":{x:document(x) for x in ["bg","en","ru","ro"]},"commercial":{"m99_selling_price":None,"stock_claim":None},"guards":{"supplier_verbatim_copy":False,"invented_claims":False,"price_in_content":False,"unverified_stock_in_content":False,"claim_level_provenance":True}}
