from copy import deepcopy
VERSION="0.6.7.4.2"
CHANNELS={"mela99.com":["bg","en","ru"],"m99.eu":["bg","en","ru"],"rabotni-drehi.com":["bg","en","ru"],"medicinski-drehi.com":["bg","en","ru"],"laviro.ro":["ro","en"],"alviro.ro":["ro","en"]}
FACTS={"brand":"Cherokee","collection":"WW Revolution","style":"WW601","supplier_alias":"WWE601","manufacturer_item":"CK-WW601--","colour":"Navy","material":"78% polyester, 20% rayon, 2% spandex","fit":"Missy relaxed fit","length":"26 in / 66.04 cm","neckline":"Curved V-neckline","sleeves":"Short sleeves","pockets":"2 front patch pockets with instrument loops","front_back_yokes":True,"mesh_side_panels":True,"shirttail_hem":True,"fabric":"Silky stretch twill fabric","supplier_visible_sizes":["2XS","XS","S","M","L","XL","2XL"]}
TEXT={
"bg":{"name":"Дамска медицинска туника Cherokee WW Revolution WW601 Navy","meta":"Cherokee WW601 Navy дамска медицинска туника","desc":"Дамска медицинска туника Cherokee WW601 Navy с еластична материя, V-образно деколте, 2 джоба и дишащи мрежести странични панели.","short":"Професионална дамска медицинска туника Cherokee WW Revolution WW601 Navy с еластична смес от полиестер, вискоза и еластан, свободна Missy кройка, два функционални предни джоба и мрежести странични панели.","sections":[["Дизайн и кройка","WW601 е дамска медицинска туника от серията WW Revolution на Cherokee. Извитото V-образно деколте, късите ръкави и оформеният долен край създават чист професионален силует и практична конструкция за активен работен ден."],["Материя и комфорт","Съставът е 78% полиестер, 20% вискоза и 2% еластан. Производителят определя тъканта като silky stretch twill. Еластичната конструкция и свободната Missy relaxed fit кройка подпомагат свободата на движение."],["Джобове и функционалност","Два предни външни джоба осигуряват място за често използвани принадлежности. Интегрирани са примки за инструменти, а предната и задната кокетка са част от конструкцията."],["Мрежести странични панели","Мрежестите странични панели са функционална особеност на модела. Cherokee ги посочва като част от дизайна за въздухопропускливост, комфорт и мобилност."],["Кройка и размери","Дължината по средата на гърба е 26 инча, приблизително 66 cm. При точния продукт на доставчика са наблюдавани размери 2XS, XS, S, M, L, XL и 2XL; това не доказва текуща наличност."],["Технически характеристики","Марка Cherokee; колекция WW Revolution; модел WW601; доставчиково означение WWE601; цвят Navy; къси ръкави; извито V-образно деколте; 2 предни джоба; мрежести странични панели."]]},
"en":{"name":"Cherokee WW Revolution WW601 Navy Women's Scrub Top","meta":"Cherokee WW601 Navy Women's Scrub Top","desc":"Cherokee WW601 Navy women's scrub top with stretch twill, curved V-neck, 2 front pockets, instrument loops and breathable mesh side panels.","short":"Cherokee WW Revolution WW601 Navy women's scrub top with silky stretch twill, Missy relaxed fit, two front patch pockets and breathable mesh side panels.","sections":[["Design and fit","WW601 is a women's scrub top from Cherokee's WW Revolution collection. Its curved V-neckline, short sleeves and shirttail hem create a clean professional profile for an active working day."],["Fabric and comfort","The fabric is 78% polyester, 20% rayon and 2% spandex. Cherokee describes it as silky stretch twill. The stretch construction and Missy relaxed fit support comfortable movement."],["Pockets and functionality","Two front patch pockets provide accessible storage and include instrument loops. Front and back yokes form part of the garment construction."],["Breathable mesh side panels","Mesh side panels are a functional feature of the style. Cherokee highlights breathable mesh in relation to comfort and mobility."],["Fit and sizes","Center-back length is 26 inches, approximately 66 cm. Sizes observed on the exact supplier product were 2XS, XS, S, M, L, XL and 2XL; this does not certify current stock."],["Technical specifications","Brand Cherokee; collection WW Revolution; style WW601; supplier alias WWE601; Navy; short sleeves; curved V-neckline; 2 front patch pockets; mesh side panels."]]},
"ru":{"name":"Женская медицинская туника Cherokee WW Revolution WW601 Navy","meta":"Cherokee WW601 Navy женская медицинская туника","desc":"Женская медицинская туника Cherokee WW601 Navy: эластичная ткань, V-образный вырез, 2 передних кармана и дышащие сетчатые панели.","short":"Женская медицинская туника Cherokee WW Revolution WW601 Navy из эластичной смеси полиэстера, вискозы и эластана, со свободной посадкой Missy, двумя карманами и сетчатыми боковыми панелями.","sections":[["Дизайн и посадка","WW601 — женская медицинская туника из коллекции Cherokee WW Revolution. Изогнутый V-образный вырез, короткие рукава и фигурный нижний край формируют аккуратный профессиональный силуэт."],["Материал и комфорт","Состав: 78% полиэстер, 20% вискоза и 2% эластан. Производитель характеризует ткань как silky stretch twill. Эластичная конструкция и Missy relaxed fit рассчитаны на свободу движения."],["Карманы и функциональность","Два передних накладных кармана дают место для принадлежностей и имеют петли для инструментов. Передняя и задняя кокетки являются частью конструкции."],["Сетчатые боковые панели","Сетчатые боковые панели — функциональная особенность модели, которую Cherokee связывает с комфортом и мобильностью."],["Посадка и размеры","Длина по центру спинки 26 дюймов, около 66 см. У точного товара поставщика наблюдались размеры 2XS–2XL; это не подтверждение текущего остатка."],["Технические характеристики","Cherokee; WW Revolution; WW601; код поставщика WWE601; Navy; короткие рукава; V-образный вырез; 2 передних кармана; сетчатые боковые панели."]]},
"ro":{"name":"Bluză medicală damă Cherokee WW Revolution WW601 Navy","meta":"Cherokee WW601 Navy bluză medicală damă","desc":"Bluză medicală damă Cherokee WW601 Navy cu material elastic, decolteu în V, 2 buzunare frontale și panouri laterale respirabile din plasă.","short":"Bluză medicală damă Cherokee WW Revolution WW601 Navy, din amestec elastic de poliester, viscoză și elastan, cu croială Missy relaxată, două buzunare și panouri laterale din plasă.","sections":[["Design și croială","WW601 este o bluză medicală pentru femei din colecția Cherokee WW Revolution. Decolteul curbat în V, mânecile scurte și tivul de tip shirttail creează un aspect profesional."],["Material și confort","Compoziția este 78% poliester, 20% viscoză și 2% elastan. Cherokee descrie materialul drept silky stretch twill. Construcția elastică și Missy relaxed fit susțin libertatea de mișcare."],["Buzunare și funcționalitate","Două buzunare frontale aplicate oferă spațiu accesibil și includ bucle pentru instrumente. Modelul include jug frontal și posterior."],["Panouri laterale respirabile","Panourile laterale din plasă sunt un element funcțional al modelului, asociat de Cherokee cu confortul și mobilitatea."],["Croială și mărimi","Lungimea centrală la spate este 26 inch, aproximativ 66 cm. La produsul exact al furnizorului au fost observate mărimile 2XS–2XL; acestea nu confirmă stocul curent."],["Specificații tehnice","Cherokee; WW Revolution; WW601; alias furnizor WWE601; Navy; mâneci scurte; decolteu în V; 2 buzunare frontale; panouri laterale din plasă."]]}
}
FAQ={"bg":[["Каква е материята?","78% полиестер, 20% вискоза и 2% еластан."],["Колко джоба има?","Два предни джоба с примки за инструменти."],["Каква е кройката?","Missy relaxed fit."],["Има ли мрежести панели?","Да, странични мрежести панели."],["Каква е дължината?","26 инча, приблизително 66 cm."],["Какви размери са наблюдавани?","2XS–2XL; това не доказва текуща наличност."],["Какъв е кодът?","WW601; доставчикът използва и WWE601."],["Какво е деколтето?","Извито V-образно деколте."]],"en":[["What is the fabric?","78% polyester, 20% rayon and 2% spandex."],["How many pockets?","Two front patch pockets with instrument loops."],["What fit?","Missy relaxed fit."],["Mesh panels?","Yes, mesh side panels."],["Length?","26 inches, approximately 66 cm."],["Observed supplier sizes?","2XS–2XL; not a current-stock claim."],["Style code?","WW601; supplier alias WWE601."],["Neckline?","Curved V-neckline."]],"ru":[["Какой состав?","78% полиэстер, 20% вискоза и 2% эластан."],["Сколько карманов?","Два передних кармана с петлями."],["Какая посадка?","Missy relaxed fit."],["Есть сетчатые панели?","Да, боковые."],["Длина?","26 дюймов, около 66 см."],["Размеры у поставщика?","2XS–2XL; это не текущий остаток."],["Код модели?","WW601; также WWE601."],["Какой вырез?","Изогнутый V-образный."]],"ro":[["Care este compoziția?","78% poliester, 20% viscoză și 2% elastan."],["Câte buzunare?","Două buzunare frontale cu bucle."],["Ce croială?","Missy relaxed fit."],["Are plasă laterală?","Da."],["Lungime?","26 inch, aproximativ 66 cm."],["Mărimi observate?","2XS–2XL; nu confirmă stocul."],["Cod model?","WW601; alias WWE601."],["Decolteu?","Curbat în V."]]}
def render(d,faq):
 s=[f"<h1>{d['name']}</h1>",f"<p>{d['short']}</p>"]
 for h,t in d["sections"]:s += [f"<h2>{h}</h2>",f"<p>{t}</p>"]
 s+=["<h2>FAQ</h2>"]
 for q,a in faq:s += [f"<h3>{q}</h3>",f"<p>{a}</p>"]
 return "\\n".join(s)
def build():
 docs={}
 for site,langs in CHANNELS.items():
  docs[site]={}
  for lang in langs:
   d=deepcopy(TEXT[lang]);d["h1"]=d["name"];d["meta_title"]=d["meta"]+" | "+site.split(".")[0].upper();d["meta_description"]=d.pop("desc");d["short_description"]=d.pop("short");d["faq"]=FAQ[lang];d["long_description_html"]=render({**d,"short":d["short_description"]},FAQ[lang]);d["image_alt"]=[d["name"],d["name"]+" V-neck",d["name"]+" pockets",d["name"]+" mesh panels",d["name"]+" Navy"];d["keywords_entities"]=["Cherokee","WW Revolution","WW601","WWE601","Navy"];d["schema_ready_facts"]={"brand":"Cherokee","model":"WW601","color":"Navy"};d["claim_provenance"]=[{"source":"Cherokee manufacturer","fields":["material","fit","length","neckline","sleeves","pockets","front_back_yokes","mesh_side_panels","shirttail_hem","fabric"]},{"source":"Stenso exact product","fields":["supplier_alias","supplier_visible_sizes"],"stock_inference":False}];d["quality_score"]=97;docs[site][lang]=d
 return {"schema_version":VERSION,"mode":"PRODUCTION_GRADE_FULL_CONTENT_PREVIEW","write_allowed":False,"facts":FACTS,"channel_language_policy":CHANNELS,"documents":docs,"commercial":{"m99_selling_price":None,"stock_claim":None},"guards":{"supplier_verbatim_copy":False,"invented_claims":False,"price_in_content":False,"unverified_stock_in_content":False,"localization_quality":True,"channel_duplication_guard":True,"claim_level_provenance":True}}


# v0.6.7.5.4 compatibility aliases.
# The generation body above is the tested v0.6.7.4.2 content engine.
def build_documents():
    return build()

def build_all_sites_content():
    return build()
